# script to visualize gene expression data
setwd("/Users/marianasierra/Desktop/srinivasan_bulk_rna_seq")

# load libraries
library(tidyverse)
library(ggplot2)

# data Upload

# Read in the file. Don't set row names yet
# Note if using R < 4.0.0, set stringsAsFactors = FALSE in read.delim
data_1 <- read.delim("gene_expected_count.annot.txt", row.names = NULL)
# Deal with genes that don't have annotated gene symbols (external_gene_name)
# Use ENSEMBL ID if gene symbol not available
data_1$external_gene_name <- ifelse(
  data_1$external_gene_name == ".",
  data_1$gene_id,
  data_1$external_gene_name
)
# Deal with duplicated gene symbols
# Combine gene symbol with ENSEMBL ID if non-unique
data_1$external_gene_name <- ifelse(
  duplicated(data_1$external_gene_name),
  paste(data_1$external_gene_name, data_1$gene_id, sep="_"),
  data_1$external_gene_name
)
# Then we can use the gene symbol column as the row names,
# Set gene names as a separate column, not as row names
# Set gene names as a separate column, not as row names
#gene_names <- data$external_gene_name

# Subset the count data for further analysis
counts.data <- data[,5:ncol(data)] # All columns after 4 are count data

#I had this code here to change the column names so they were easier to interpret but I am just leaving it off for now 
#columns = c("1","2","3","4","5","6","7","9","10","11","12","13","14","15","16","17","19")

#This would be to change the column name using the vector we made above
#colnames(counts.data) = columns

# Add a column named "gene" to count.data containing gene names
#count.data <- cbind(gene = gene_names, count.data)

# Now count.data has "gene" as the first column containing gene names
summary(counts.data)
###0.Plotting Data ----

#basic format for ggplot
# ggplot(data, aes(x = variable, y = variable1)) +
#   geom_col()

### 1. Barplot ----
par(mar=c(8,4,4,1)+.01) #to fix margins 
barplot(colSums(counts.data)/1e6, las=3)



